/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.io.IOException;

public class App {
    public void getGreeting() throws InterruptedException, IOException {

        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");

        TestCases tests = new TestCases(); // Initialize your test class

        // TODO: call your test case functions one after other here

    //      tests.testCase01();
    //      tests.testCase02();
    //    for test case 3 the webpage is taking very long time to load  which is seen common issue with other learners and hence the code terminates with exception
 tests.testCase03();
    //      tests.testCase04();
    //      tests.testCase05();
    //     tests.testCase06();
        //here password is confidential so didnot mention the original password in sendkeys
      //  tests.testCase07();

        // END Tests

        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
